### ISSUE TITLE
More documentation on getting started

### ISSUE THREAD

**Issue by pmiddend** [wolfadex/elm-open-api#4]
I've just tried to use elm-open-api and encountered some difficulties, namely:

1. The README in this repository is very unhelpful, and it took me a while to find the actual documentation on npmjs.com. Maybe you could link that from the README, or copy the instructions?
2. It's not clear what dependencies I need to add in order to use the generated Elm code. Apparently at least `elm/bytes`?

Edit: also, running `npm run dev` (as indicated in the README on nodejs) says `Missing script: "dev"`, and I also don't see this script in `package.json`.

**Comment by wolfadex** [comment]
> The README in this repository is very unhelpful, and it took me a while to find the actual documentation on npmjs.com. Maybe you could link that from the README, or copy the instructions?

Sorry about the confusion! This repo is for the Elm package `wolfadex/elm-open-api` while https://github.com/wolfadex/elm-open-api-cli/ is for the CLI too `elm-open-api` on NPM. I hadn't thought about the confusion this would cause and I will get some docs added to this repo to help in the future.

> It's not clear what dependencies I need to add in order to use the generated Elm code. Apparently at least elm/bytes?

That's an excellent point about the dependencies! I'll create an issue in the other repo to get those added to the docs.

> also, running npm run dev (as indicated in the README on nodejs) says Missing script: "dev", and I also don't see this script in package.json.

I'm guessing that you're look at the `Development` section of that readme? That section is for working on the tool itself. If you're trying to use the tool then you want the section above that labeled `Getting Started`. I'll update those docs as well to make them more clear. I think there's a mistake in the docs as well. They currently say to run
```sh
node elm-open-api ./page/to/oas.json
```
but that should say
```sh
npx elm-open-api ./page/to/oas.json
```
---
I've created https://github.com/wolfadex/elm-open-api-cli/issues/55 and https://github.com/wolfadex/elm-open-api-cli/issues/56 to address both of the issues there. I'll use this issue to track the documentation issues here.

**Comment by pmiddend** [comment]
Ahhhh, I feel very stupid for not noticing the other project! I just listened to the Elm Radio episode and googled "elm-open-api". The results are very confusing, but that's hardly your fault. I'll retry my efforts with the other package in mind and report if anything is still weird about it.

**Comment by pmiddend** [comment]
Ah, guess I can keep this open if it still tracks something...

**Comment by wolfadex** [comment]
The usage docs and the communication about the dependencies needed when using the CLI have been updated over the past few releases. I've also added a new story for specifically updating the docs in this repo to make this side of things more clear.
