### ISSUE TITLE
Add risky variants to generated tasks and requests

### ISSUE THREAD

**Issue by myrho** [wolfadex/elm-open-api#5]
Thank you for creating this package! 

Maybe I missed it somewhere. But is there a way to get risky variants of tasks/requests generated?

**Comment by wolfadex** [comment]
I think I completely overlooked these! We can definitely get them added.

**Comment by wolfadex** [comment]
Moved to the correct repo, https://github.com/wolfadex/elm-open-api-cli/issues/71
