### ISSUE TITLE
Use path segments parameter for Url.crossOrigin

### ISSUE THREAD

**Issue by myrho** [wolfadex/elm-open-api#6]
It'd be great if the urls could be generated using `Url.crossOrigin`'s path segments parameter. In my case, an openapi endpoint `/example/{x}` results in this Elm code 
```elm
            Url.Builder.crossOrigin
                (String.replace
                    "{x}"
                    config.params.x
                    "http://example.com/example/{x}"
                )
                []
                ...
```
which then results in an url with a trailing slash `http://example.com/example/x/`. However, this then does not match the endpoint's url in the openapi spec which is without trailing slash.

Would it be possible to have the Elm code being generated like this:
```elm
            Url.Builder.crossOrigin
                "http://example.com"
                [ "example"
                , config.params.x
                ]
                ...
```

Then the resulting url would be without trailing slash and hence matching the openapi spec.

**Comment by wolfadex** [comment]
Moved to the correct repo,https://github.com/wolfadex/elm-open-api-cli/issues/72
